swagger: "2.0"

info:
  title: "Swagger Docs"
  version: 1.0

schemes: ["http", "https"]

paths:
  /string:
    get:
      summary: "Returns a string"
      description: "It just returns a fake string"
      responses:
        200:
          description: Success
          schema:
            type: "string"
            example: "A fake string"




components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []   