swagger: "2.0"

info:
  title: Blog API
  version: 1.0

schemes: ["http", "https"]

paths:
  /api/signup:
    post:
      summary: Sign up
      description: Registeration for new users
      consumes:
        - multipart/form-part
      parameters:
        - name: username
          in: formData
          required: true
        - name: email
          in: formData
          required: true
        - name: image
          in: formData
          required: true
          type: file
        - name: password
          in: formData
          required: true
        - name: confirmationpassword
          in: formData
          required: true
      responses:
        200:
          description: Successful operation
        400:
          description: Bad request
        401:
          description: Restaurant doesn't exist

components:
  schemas:
    User:
      type: object
      example:
        {
          "username": "David",
          "email": "david@email.com",
          "password": "password",
          "confirmPassword": "password",
        }
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
