name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
        
      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise automatic pull request
        uses: peter-evans/create-pull-request@v3.10.1
        with: 
          branch: create-pull-request/patch
          base: name
          title: DEMO for auto PR
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{env.GIT_COMMIT_AUTHOR_EMAIL }} >
          body: 
            This is a pull request to show automatic PR
          token: ${{ secrets.GITHUB_TOKEN }}
          delete_branch: true

